spring.application.name=JDBC_aprendendo
spring.datasource.url=jdbc:mysql://localhost:3306/aula_jdbc
spring.datasource.username=root
spring.datasource.password=012030@vC
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver